spring.application.name=poll
server.port=8081
# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/poll?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Lifecycle & SQL Logging Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
